# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macOS-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: 'app'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
    jdkVersionOption: 1.17

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'app/build/outputs/apk/debug'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'app/build/test-results/testDebugUnitTest/'
    testRunTitle: 'Build test'
    buildPlatform: 'Gradle'
    buildConfiguration: 'assembleDebug'