# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: 'SchoolHard'
    pipeline: 'Build'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: 'build'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'Appcenter'
    appSlug: 'SQ8/SchoolHard'
    appFile: 'build/drop/app-debug.apk'
    buildVersion: '0.0.3'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New release'
    destinationType: 'groups'
    distributionGroupId: 'dd76dfed-123b-4b4c-8d25-284939037c41'