# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- '*'

pool:
  vmImage: 'macos-latest'


steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'gradle.properties'

- task: CopyFiles@2
  inputs:
    Contents: 'gradle.properties'
    TargetFolder: 'app'
    
- task: Gradle@3
  inputs:
    workingDirectory: 'app'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'app/build/outputs/apk/release/'
    artifact: 'ReleaseAPK'
    publishLocation: 'pipeline'