trigger:
- main

pool:
  vmImage: 'macOS-latest'

steps:
- task: Gradle@3
  inputs:
    workingDirectory: 'app'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
    jdkVersionOption: 1.17